name: Nutrobo Android Build
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repository
        uses: actions/checkout@v4
      - name: Test Connection
        run: curl "https://storage.googleapis.com/flutter_infra_release/releases/releases_linux.json"
      - name: Configure Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version-file: pubspec.yaml # path to pubspec.yaml
      - name: Build Android App
        run: flutter --version && flutter build apk