name: Nutrobo Android Build
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repository
        uses: actions/checkout@v4
      - name: Configure Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          version: 1.0.0
      - name: Build Android App
        run: flutter --version && flutter build apk